language: python

branches:
  only:
    - master

services:
  - docker

env:
  - PARSEC_VERSION=3.0
  - TAG=latest

script:
  - docker pull ${TRAVIS_REPO_SLUG}:${TAG} || true
  - >
    docker build 
    -t ${TRAVIS_REPO_SLUG}:${TAG}
    --build-arg PARSEC_VERSION=${PARSEC_VERSION}
    --cache-from ${TRAVIS_REPO_SLUG}:${TAG}
    .
after_success:
  - >
    if [ $TRAVIS_BRANCH = 'master' ] && [ $TRAVIS_PULL_REQUEST = 'false' ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      docker push ${TRAVIS_REPO_SLUG}:${TAG}
    fi